os: linux
dist: bionic
language: python
python: "3.7"


matrix:
  include:

    - name: "GCC Linux Bionic Release"
      addons:
        apt:
          packages:
            - doxygen
      os: linux
      dist: bionic
      compiler: gcc
      env:
        - BUILD_TYPE=Release
        - GENERATOR="Unix Makefiles"
      after_success:
        # Build documentation
        - cd .. && doxygen Doxyfile
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: docs/html
        github_token: $GH_REPO_TOKEN
        on:
          branch: master

    - name: "GCC OSX Release"
      os: osx
      osx_image: xcode11.4
      language: minimal
      compiler: gcc
      env:
        - BUILD_TYPE=Release
        - GENERATOR="Unix Makefiles"

    - name: "GCC Linux Bionic Debug"
      os: linux
      dist: bionic
      compiler: gcc
      env:
        - BUILD_TYPE=Debug
        - GENERATOR="Unix Makefiles"

    - name: "GCC OSX Debug"
      os: osx
      osx_image: xcode11.4
      language: minimal
      compiler: gcc
      env:
        - BUILD_TYPE=Debug
        - GENERATOR="Unix Makefiles"

install:
# Install and configure conan
  - pip install conan
  - conan user

script:
# Build software and run tests
  - mkdir build && cd build
  - cmake -G "$GENERATOR" -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - cmake --build .
  - ctest
