sudo: required
language: python
python: "3.7"

matrix:
  include:
    - name: "Linux Bionic Release"
      os: linux
      dist: bionic
      compiler: gcc
      env:
        - BUILD_TYPE=Release
        - GENERATOR="Unix Makefiles"
      script:
        - mkdir build && cd build
        - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
        - cmake --build .
        - ctest
    - name: "Linux Bionic Debug"
      os: linux
      dist: bionic
      compiler: gcc
      env:
        - BUILD_TYPE=Debug
      script:
        - mkdir build && cd build
        - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
        - cmake --build .
        - ctest

install:
# Install and configure conan
  - pip install conan
  - conan user