sudo: required
language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - python3
            - python3-pip
            - python3-setuptools
      compiler: gcc
      env:
        - BUILD_TYPE=Release
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - python3
            - python3-pip
            - python3-setuptools
      compiler: gcc
      env:
        - BUILD_TYPE=Debug

install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip list --format freeze --outdated | sed 's/=.*//g' | xargs -n1 python3 -m pip install -U
  - python3 -m pip install conan
  - conan user

script:
# Download dependencies and build project
  - mkdir build && cd build
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - cmake --build .
# Run tests
  - ctest