sudo: required
language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - deadsnakes
          packages:
            - python3.7
            - python3-pip
      compiler: gcc
      env:
        - BUILD_TYPE=Release
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - deadsnakes
          packages:
            - python3.7
            - python3-pip
      compiler: gcc
      env:
        - BUILD_TYPE=Debug

before_install:
# Install pip and conan
  - python3.7 -m pip install pip
  - python3.7 -m pip install --upgrade pip
  - python3.7 -m pip install conan

install:
  - conan user

script:
# Download dependencies and build project
  - mkdir build && cd build
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - cmake --build .
# Run tests
  - ctest