sudo: required
language: python
python: "3.7"

matrix:
  include:
    - name: "Linux Bionic Release"
      os: linux
      dist: bionic
      compiler: gcc
      env:
        - BUILD_TYPE=Release
        - GENERATOR="Unix Makefiles"

    - name: "Linux Bionic Debug"
      os: linux
      dist: bionic
      compiler: gcc
      env:
        - BUILD_TYPE=Debug
        - GENERATOR="Unix Makefiles"

    - name: "OSX Release"
      os: osx
      osx_image: xcode8
      compiler: gcc
      env:
        - BUILD_TYPE=Debug
        - GENERATOR="Unix Makefiles"

install:
# Install and configure conan
  - pip install conan
  - conan user

script:
  - mkdir build && cd build
  - cmake -G "$GENERATOR" -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - cmake --build .
  - ctest