os: linux
sudo: required
language: python
python: "3.7"
dist: xenial
compiler:
  - gcc
install:
# Install conan
  - pip install conan
# Automatic detection of arch, compiler, etc.
  - conan user
script:
# Download dependencies and build project
  - mkdir build && cd build
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
  - make
# Run tests
  - ctest