sudo: required
os: linux
language: python
python: "3.7"
dist: xenial

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - BUILD_TYPE=Release
    - os: linux
      compiler: gcc
      env:
        - BUILD_TYPE=Debug

install:
# Install conan
  - pip install conan
  - conan user

script:
# Download dependencies and build project
  - mkdir build && cd build
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make
# Run tests
  - ctest