sudo: required
language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - deadsnakes
          packages:
            - python3.7
      compiler: gcc
      env:
        - BUILD_TYPE=Release
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - deadsnakes
          packages:
            - python3.7
      compiler: gcc
      env:
        - BUILD_TYPE=Debug

install:
# Install conan
  - pip3 install conan
  - conan user

script:
# Download dependencies and build project
  - mkdir build && cd build
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - cmake --build .
# Run tests
  - ctest