version: 1.0.{build}

platform:
  - x64

install:
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
  - cmd: conan user
  - cmd: conan --version

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake --help
  - cmd: cmake -G "Visual Studio 16 2019 Win64" ..
  - cmd: cmake --build . --config Release

test_script:
  - cmd: cd test\Release
  - cmd: udp-packet-replicator-test.exe