version: 1.0.{build}

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Release
  - Debug

install:
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
  - cmd: conan user
  - cmd: conan --version

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -G "Visual Studio 15 2017 Win64" ..
  - cmd: cmake --build . --config %CONFIGURATION%

test_script:
  - cmd: cd test\%CONFIGURATION%
  - cmd: udp-packet-replicator-test.exe
